name: Build and Release Executable

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --noconsole --onefile --icon=favicon/favicon.ico --add-data "favicon;favicon" --version-file=version.txt --name pyrics main.py

      - name: Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pyrics.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
